language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install -r user_service/requirements.txt
  - pip install -r todo_service/requirements.txt

# command to run tests
script:
  - nosetests
  - python user_service/manage.py test user_app
  #- python todo_service/manage.py test todo_app
  #- python user_service/manage.py runserver 0:5000
